openapi: 3.0.2
info:
  description: >- 
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard 
      dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
      It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
      It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently 
      with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.


      Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, 
      making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the 
      more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, 
      discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" 
      (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. 
      The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.


      There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, 
      by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, 
      you need to be sure there isn't anything embarrassing hidden in the middle of text. 

  title: "Template Deno"
  version: "1.0.0"

servers:
  - url: "{protocol}://{host}:{port}/{baseUrl}"
    description: ""
    variables:
      protocol:
        default: http
        enum:
          - http
          - https
        description: The protocol used to access the server.
      host:
        default: localhost
        description: The hostname or IP address of the server.
      port:
        default: "3000"
        description: The port number on which the server is listening for requests
      baseUrl:
        default: ""
        description: The base URL path for all API endpoints. This can be used to group related endpoints together under a common path.

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

tags:
  - name: Hello
    description: This is a simple example of an OpenAPI definition

paths:
  ############################################################################
  # Hello World
  ############################################################################
  /api/v1/hello/{parameter}:
    get:
      tags:
        - Hello
      summary: Example summary
      operationId: getHello
      parameters: 
        - in: path
          name: parameter
          schema:
            type: string
            example: "world"
          required: true
          description: Example parameter
      responses:
        200:
          description: Success